### ISSUE TITLE
Failed with error code 0x1C01000B

### ISSUE THREAD

**Issue by projectboot** [Kevin-Robertson/Invoke-TheHash#2]
when, i send it command more than 3847 length, im getting this error

Any idea to fix this?

**Comment by Kevin-Robertson** [comment]
I actually haven't tested for max command length. I know I haven't tried one much over 1200 chars. 3847 works? I'll take a look tonight to see what's going on with longer commands.

**Comment by projectboot** [comment]
yes, i tried now. 3863 worked. but 3864 failed.

**Comment by Kevin-Robertson** [comment]
Okay cool, thanks, I'll go through and replicate that.

**Comment by Kevin-Robertson** [comment]
Comparing the behavior to Invoke-WMIMethod, it looks like another packet is employed once a command hits a certain length. I haven't checked the protocol specs yet for details. I should be able add some code in to handle the longer commands though.

**Comment by projectboot** [comment]
hey, i working on this code since from 2 day. but still dont work.

Maybe problem is from BitConverter line 199.
What's your idea?

**Comment by Kevin-Robertson** [comment]
It's more down around the line 1220 section. Logic will need to be added to split the RPC request over multiple packets (using the appropriate first and last flags) for longer commands.

**Comment by projectboot** [comment]
kevin, its rly perfect code.
me and our friends still waitting for fix.

can u look code, when u r available?

Thx.

**Comment by Kevin-Robertson** [comment]
Yeah, I'll be working on it more this weekend. There is a similar issue with Invoke-SMBExec and Inveigh-Relay that I need to fix so they work with the longer Empire 2 launchers.

**Comment by Kevin-Robertson** [comment]
Added support for longer commands to both Invoke-WMIExec and Invoke-SMBExec.
