### ISSUE TITLE
SMB-Finger in powershell

### ISSUE THREAD

**Issue by lordsaibat** [Kevin-Robertson/Invoke-TheHash#5]
Kevin,
    Trying to recreate https://github.com/lgandx/Responder/blob/master/tools/RunFinger.py in powershell. 
According to the SMBFinger function need to send command 72, flag1 x18, flag2 x53 xC8. I think I got that but not sure how to send and pull the data. 
Here is what I got so far, but I could be way off:

function Get-SmbFinger()
{
    $SMB_client_stream = $SMB_client.GetStream()
    $SMB_client_receive = New-Object System.Byte[] 81920
    $packet_SMB_header = Get-PacketSMBHeader 0x72 0x18 0x53,0xC8 0xff,0xff $process_ID_bytes[0,1] 0x00,0x00       
    $packet_SMB_data = Get-PacketSMBNegotiateProtocolRequest $SMB_version
    $SMB_header = ConvertFrom-PacketOrderedDictionary $packet_SMB_header
    $SMB_data = ConvertFrom-PacketOrderedDictionary $packet_SMB_data
    $packet_NetBIOS_session_service = Get-PacketNetBIOSSessionService $SMB_header.Length $SMB_data.Length
    $NetBIOS_session_service = ConvertFrom-PacketOrderedDictionary $packet_NetBIOS_session_service
    $SMB_client_send = $NetBIOS_session_service + $SMB_header + $SMB_data
    $SMB_client_stream.Write($SMB_client_send,0,$SMB_client_send.Length)
    $SMB_client_stream.Flush()    
    $SMB_client_stream.Read($SMB_client_receive,0,$SMB_client_receive.Length)

}

Let me know what you think.

**Comment by Kevin-Robertson** [comment]
Sorry for the delay, I've been off the grid a little. Are you generating any network traffic at all with that? What errors do you get? You would also need the functions (Get-PacketSMBHeader,etc) and the connection setup code.
